# Generated by Django 4.1.3 on 2023-02-09 16:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="electronic_items_earphones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("description", tinymce.models.HTMLField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stocks", models.IntegerField()),
                ("color", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="electronic_items_mobiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("description", tinymce.models.HTMLField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stocks", models.IntegerField()),
                ("color", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="electronic_items_watch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("description", tinymce.models.HTMLField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stocks", models.IntegerField()),
                ("color", models.CharField(max_length=20)),
            ],
        ),
    ]
